[[redirects]]
  from = "/https://nwqohp1ofa.execute-api.eu-central-1.amazonaws.com/smartrep-live-count?"
  to = "<cross-origin-url>"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"